name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: install python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10

      - name: install testing dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: run tests
        run: pytest

      - name: build docker image
        run: |
          docker build -t fastapi-docker-gh-actions-demo --build-arg ENV=PROD .
